### ISSUE TITLE
MacOS 14.4.1 (23E224) is rejected

### ISSUE THREAD

**Issue by yuankailiu** [alptugan/icns-creator#7]
Hi, will this work on 14.4.1? I tried open it but it said not supporting on this Mac.

**Comment by alptugan** [comment]
It runs on 14.6.1.
Did you check installation instructions? Since the app is not signed by Apple, it may cause such issues. 
You need to enable System Settings->Privacy & Security->Security->App Store and identified developers option.
Sometimes, depending on your configuration, you need to disable "Gate keeper" option to install unsigned apps.
You can have more information [link](https://www.macworld.com/article/672947/how-to-open-a-mac-app-from-an-unidentified-developer.html)

OR
If you install XCode, you can compile the app in your system.

**Comment by yuankailiu** [comment]
Right, I did the same thing as here. Also I tried `sudo spctl --master-disable` in that link. However, it is still shown as blocked and not supported. I may have to learn to use the Xcode to compile it. Thank you.

<img width="687" alt="image" src="https://github.com/user-attachments/assets/aabbfdfd-4481-4eb9-a30f-a7302cc72a99">

<img width="372" alt="image" src="https://github.com/user-attachments/assets/1ac76f7a-a03f-46ff-a53d-79e2a809be68">

**Comment by alptugan** [comment]
What is your laptop chip? Is it M1 or M2? The other machine I've tested is also M2. 

You can easily compile the application, by the way. 
Clone or download the repository on your computer. 
Open the zip folder.
Then double click on the `icns creator.xcodeproj` file. 
It will open the project in XCode and press the Run button.

**Comment by dotvhs** [comment]
I'm on Intel, Sonoma 14.5 and also can't run it. Is this application only for Apple Silicon?

**Comment by yuankailiu** [comment]
I am also intel core i9.

Now I compiled it. Thank you.
But the compiled app is under `/Users/ykliu/Library/Developer/Xcode/DerivedData/icns_creator-dkrdurhnmpvjsydfyzjfqhckrwiw/Build/Products/Debug`

I then copy that to the Applications directory.

**Comment by alptugan** [comment]
@dotvhs @yuankailiu I tested older versions on my Intel macbook. They worked fine. So, it shouldn't be a problem for Intel based machines.

Instead of using Debug product, it is better to choose Release version. 

@yuankailiu you can access the compiled version from Xcode menu.

Also, I released a patched version 3.5.1 as prerelease for macOS 14+ you can try to run this version if your system is above 14.
Let me know if it works out or not.

**Comment by dotvhs** [comment]
> Let me know if it works out or not.

![CleanShot 2024-09-16 at 20 14 41@2x](https://github.com/user-attachments/assets/e2fc865c-81dc-4f19-b4ce-153cab25c83e)

Still a no from me, I'm on 14.5

**Comment by alptugan** [comment]
> Still a no from me, I'm on 14.5

Ok. I will check the on my old Intel-based Mac also. 
Thanks for the feedback @dotvhs

**Comment by alptugan** [comment]
@dotvhs and @yuankailiu , I submit a pre-relelase for Intel-based Macs. It seems to be fine on my mid-2015 macos 12.7.6. 

Let me know if it works on your machines. 

https://github.com/alptugan/icns-creator/releases/tag/v3.5.3

**Comment by dotvhs** [comment]
> Let me know if it works on your machines.

It finally launches, yes! Thank you for your work. For some reason it is unable to save .icns though but it finally launches now. When I press "Generate .icns" - nothing happens. Generating .iconset seems to be working fine though, it opens save file dialog.

Also unrelated (i think?) minor bug is that when I tab out and tab back, the app window changes its size and all the options are invisible.

Still, thank you for your work!

**Comment by alptugan** [comment]
@dotvhs For now, the app saves files to the source image directory. I will fix the save issue.

"the app window changes its size and all the options are invisible."
Actually two tabs are different form each other. The options in .icns are not available for .iconset mode.
.iconset -> creates the iconset folder and creates a single icns file.
.icns -> it allows you to create icns files in specific resolutions.

**Comment by yuankailiu** [comment]
Great! thanks very much! It works for me as well.
